language: objective-c
before_install:
  - nvm install 12
  - npm install
  - gem install xcpretty
  - gem install cocoapods
  - pod install --project-directory=ios
before_script:
  - npm run compile:test
script:
  - npm test
